blank_issues_enabled: true
contact_links:
  - name: ğŸ Instructions to include environment details
    url: https://github.com/arnoudkooi/SN-Utils/blob/master/.github/template.md
    about: Please read the instruction to ensure you include the environment details.
