blank_issues_enabled: false
contact_links:
  - name: ğŸ Bug report
    url: https://github.com/arnoudkooi/SN-Utils/issues/new?template=bug_report.yml
    about: Report a new Issue, be sure to search first and include the requested details.
  - name: ğŸ’¬ Feature Request or General Question?
    url: https://github.com/arnoudkooi/SN-Utils/discussions/new/choose
    about: Use GitHub Discussions for ideas or questions. Issues are for bugs only.
  - name: â„¹ Instructions to include environment details
    url: https://github.com/arnoudkooi/SN-Utils/blob/master/.github/template.md
    about: Please read the instruction to ensure you include the environment details.
