blank_issues_enabled: false
contact_links:
  - name: ğŸ Report a Bug (after reading the guidelines)
    url: https://github.com/arnoudkooi/snutils/blob/main/.github/guideline.md
    about: Please read the reporting guidelines first to ensure you include the environment details.
